AWSTemplateFormatVersion: 2010-09-09
Description: Conditions Practice
Parameters:
  MyKeyName:
    Description: Select Key name
    Type: AWS::EC2::KeyPair::KeyName
    Default: awskey
  EnvironmentName:
    Description: Select the environment 
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
    ConstraintDescription: must be development or production      
Mappings:     
  MyRegionMap:
    us-east-1:
      HVM64: ami-09d95fab7fff3776c
    us-west-2:
      HVM64: ami-0e34e7b9ca0ace12d
  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small            
234
    Properties:
      InstanceId: !Ref MyVMInstance